### ISSUE TITLE
Species Report Does Not Work as Expected

### ISSUE THREAD

**Issue by hmthomas** [NCPN/upland#99] opened 2017-04-02 00:20 UTC
[Screen_Captures_20170401.docx](https://github.com/NCPN/upland/files/888155/Screen_Captures_20170401.docx)
The species report is generating either a syntax error (#3075) or a data type mismatch error (#3464) when running the report for park-year-plot or park-plot (e.g., ARCH-2016-4 or ARCH-1). I can provide screen captures if needed. The species report is one of the reports the crew is supposed to run upon completing a plot. We had originally envisioned this report being included on the Plot Check form, but I'm thinking that can't be easily done at this point. 

I am wondering whether it's a data error. The report was working in the previous version of the database. Field lead was able to generate all the reports for the 2017 ARCH and CANY plots.  When I tried to run the report using the previous version just now, it worked initially (I think I selected ARCH only). However, it subsequently started generating the above errors and I could not get it to generate a report again trying various park-plot combinations.

**Comment by blcampbell-NCPN** [comment] 2017-04-03 05:11
**NOTE** 
Species report and its underlying tables and queries were not modified for 2017 Pre-Season Updates II.

**Background**
The underlying query which provides data for these reports is qry_Sp_Rpt_All which creates the temporary table  temp_Sp_Rpt_by_Park_Complete  . 

When qry_Sp_Rpt_All is run against the master database it runs successfully. However the next query which generates temp_Sp_Rpt_by_Park_Complete fails with an 'Invalid Use of Null' error and temp_Sp_Rpt_by_Park_Complete is not regenerated.

Breaking down this query by removing fields (some of which concatenate qry_Sp_Rpt_All fields) shows removing ParkPlotSpecies, and ParkSpecies results in a successful query. The commonality between these two fields is the Utah_Species field.

**Issue**
Review of the 36969 records produced by qry_Sp_Rpt_All shows two records lack Utah_Species data.

![missing_utah_sp_1](https://cloud.githubusercontent.com/assets/9699622/24595976/8c5ef0da-17f8-11e7-9509-5585554d57b6.PNG)

![missing_utah_sp_2](https://cloud.githubusercontent.com/assets/9699622/24595978/90c03648-17f8-11e7-8d28-c4b4eb88fc02.PNG)

Alterations of the query to avoid these two records properly generate the temp_Sp_Rpt_by_Park_Complete table which provides information for species reports.

This includes both removing 2008 records, CURE records for plots 271 and 282.
Additionally running the query only for these records reproduces the problem.

**Recommended Action**
Determine what the two Utah_Species values should be and populate these fields.

**Comment by blcampbell-NCPN** [comment] 2017-04-03 13:23
**NOTE** 
Until the data issue is resolved with these two records, temp_Sp_Rpt_by_Park_Complete which underlies species reports will not be properly generated for back-ends which include the two 2008 CURE records.

**CLOSING**
Data issue. Not a bug.

**Closed as completed by blcampbell-NCPN** 2017-04-03 13:23 UTC
Labels: P2 - High, data issue
